// Midsummer Slots — symbol registry.
//
// Sprites that came from the user's concept art are referenced via Lovable
// Asset pointers (`*.asset.json`). Sprites generated by the agent live as
// plain PNG imports in `src/assets/sprites/`.

import fireflyImg from "@/assets/sprites/firefly.png";
import fernImg from "@/assets/sprites/fern.png";
import lanternImg from "@/assets/sprites/lantern.png";
import dandelionImg from "@/assets/sprites/dandelion.png";
import mothImg from "@/assets/sprites/moth.png";
import cloverImg from "@/assets/sprites/clover.png";
import rabbitImg from "@/assets/sprites/rabbit.png";
import owlImg from "@/assets/sprites/owl.png";
import honeybeeImg from "@/assets/sprites/honeybee.png";
import crowImg from "@/assets/sprites/crow.png";
import hedgehogImg from "@/assets/sprites/hedgehog.png";

import mushroomAsset from "@/assets/sprites/mushroom.png.asset.json";
import foxAsset from "@/assets/sprites/fox.png.asset.json";

export type SymbolId =
  | "firefly"
  | "fern"
  | "mushroom"
  | "fox"
  | "lantern"
  | "dandelion"
  | "moth"
  | "clover"
  | "rabbit"
  | "owl"
  | "honeybee"
  | "crow"
  | "hedgehog";

export interface SymbolDef {
  id: SymbolId;
  name: string;
  sprite: string;
  baseOrbs: number;
  description: string;
}

export const SYMBOLS: Record<SymbolId, SymbolDef> = {
  firefly: { id: "firefly", name: "Firefly", sprite: fireflyImg, baseOrbs: 1, description: "+1 Light Orb." },
  fern: { id: "fern", name: "Fern", sprite: fernImg, baseOrbs: 1, description: "+1 Light Orb." },
  mushroom: { id: "mushroom", name: "Mushroom", sprite: mushroomAsset.url, baseOrbs: 1, description: "+1 Orb. 3+ on board: +1 Bloom Shard." },
  fox: { id: "fox", name: "Fox", sprite: foxAsset.url, baseOrbs: 3, description: "+3 Light Orbs." },
  lantern: { id: "lantern", name: "Lantern", sprite: lanternImg, baseOrbs: 3, description: "+3 Orbs. Adjacent symbols +1 (orthogonal)." },
  dandelion: { id: "dandelion", name: "Dandelion", sprite: dandelionImg, baseOrbs: 1, description: "+1 Orb. +1 Ember every 4 spins it appears." },
  moth: { id: "moth", name: "Moth", sprite: mothImg, baseOrbs: 2, description: "+2 Light Orbs." },
  clover: { id: "clover", name: "Clover", sprite: cloverImg, baseOrbs: 1, description: "+1 Orb. 10% chance to double itself." },
  rabbit: { id: "rabbit", name: "Rabbit", sprite: rabbitImg, baseOrbs: 2, description: "+2 Light Orbs." },
  owl: { id: "owl", name: "Owl", sprite: owlImg, baseOrbs: 3, description: "+3 Light Orbs." },
  honeybee: { id: "honeybee", name: "Honeybee", sprite: honeybeeImg, baseOrbs: 3, description: "+3 Light Orbs." },
  crow: { id: "crow", name: "Crow", sprite: crowImg, baseOrbs: 3, description: "+3 Light Orbs." },
  hedgehog: { id: "hedgehog", name: "Hedgehog", sprite: hedgehogImg, baseOrbs: 2, description: "+2 Light Orbs." },
};

// The starting pool is a MULTISET: duplicates increase a symbol's appearance
// odds. rollGrid() samples this array with replacement, so two Fireflies and
// two Ferns means early grids are mostly Fireflies and Ferns.
export const STARTING_POOL: SymbolId[] = [
  "firefly",
  "firefly",
  "fern",
  "fern",
  "mushroom",
  "fox",
  "lantern",
  "dandelion",
];

export const DRAFT_POOL: SymbolId[] = [
  "moth",
  "clover",
  "rabbit",
  "owl",
  "honeybee",
  "crow",
  "hedgehog",
];